# 搜索引擎配置
engines:
  baidu:
    url: https://www.baidu.com/
    feedback_url: ""
    cookie_file: baidu.com.txt
  bing:
    url: https://cn.bing.com/
    feedback_url: https://www.bing.com/webmasters/tools/contentremoval
    cookie_file: bing.com.txt
  toutiao:
    url: "https://so.toutiao.com/search?dvpf=pc&source=input&keyword={keyword}"
    feedback_url: ""
    cookie_file: toutiao.com.txt
  so360:
    url: "https://www.so.com"
    feedback_url: https://info.so.com/cache_remove.html
    cookie_file: so.com.txt
  sogou:
    url: "https://www.sogou.com"
    feedback_url: "https://fankui.sogou.com/index.php/web/web/index?type=2"
    cookie_file: sogou.com.txt
    qualification_images:
      - "business_license.jpg"
      - "trademark.jpg"
      - "authorization.jpg"

# 全局配置
qualification_dir: "company_qualifications"  # 资质图片存储目录

# 搜索关键词
keywords:
  - '91y打鱼账号下分计划'
  - '91y商人下分多平台互通'
  - '91y棋牌自动下分脚本'
  - '91y捕鱼提现攻略'
  - '91y游戏币限时提现活动'
  - '91y打鱼金币上下分策略'
  - '91y商人24小时接单'
  - '91y棋牌金币提现商城'
  - '91y捕鱼VIP专属上下客服'
  - '91y游戏金币上下交易'
  - '91y打鱼金币回购'
  - '91y商人认证上下分'
  - '91y棋牌代刷团队'
  - '91y捕鱼上下服务'
  - '91y游戏金币交易市场'
  - '91y打鱼金币提现通道'
  - '91y商人信誉上下'
  - '91y棋牌银商对接平台'
  - '91y捕鱼金币兑换中心'
  - '91y游戏币回收流程'
  - '91y回收下分认证'
  - '91y游戏币跨区交易'
  - '91y金币下分账号解封'
  - '91y交易下分靠谱推荐'
  - '91y回收账号注册'
  - '91y金币交易协议'
  - '91y游戏币转赠功能'
  - '91y回收价格波动'
  - '91y官方下分客服热线'
  - '91y金币交易手续费'
  - '91y游戏币回收限额'
  - '91y交易下分设置'
  - '91y金币回收时间表'
  - '91y高价收分微信群'
  - '91y游戏币转账风险'
  - '91y交易下分老店公示'
  - '91y金币回收公众号'
  - '91y新手卖分教程'
  - '91y官方回收二维码'
  - '91y金币交易论坛'
  - '91y秒发分联系方式'
  - '91y游戏币回收APP'
  - '91y下分交易安全保障'
  - '91y金币兑换支付宝'
  - '91y客服下分V号直通'
  - '91y金币交易贴吧'
  - '91y自动上下分系统'
  - '91y高价收分广告'
  - '91y游戏币转现教程'
  - '91y金币回收二维码'
  - '91y交易下分处理'
  - '91y正规回收渠道'
  - '91y游戏币变现技巧'
  - '91y金币回购政策'
  - '91y实时到账微信'
  - '91y代理加盟咨询'
  - '91y金币转售服务'
  - '91y下分交易风险提示'
  - '91y官方下分兑换入口'
  - '91y游戏币回收价目表'
  - '91y金币出售平台'
  - '91y客服在线收分'
  - '91y新手下分交易指南'
  - '91y高价回收金币'
  - '91y金币交易群号'
  - '91y安全提现教程'
  - '91y游戏币转账教程'
  - '91y微信秒发分'
  - '91y金币回收官网'
  - '91y信誉商家名单'
  - '91y官方合作代理'
  - '91y实时下分汇率查询'
  - '91y金币交易市场'
  - '91y快速到账渠道'
  - '91y账号安全交易'
  - '91y担保交易平台'
  - '91y自动兑换下分系统'
  - '91y游戏币下分流程'
  - '91y全天候回收客服'
  - '91y金币秒到账'
  - '91y下分流程详解'
  - '91y银商系统自动派分'
  - '91y老玩家推荐银商'
  - '91y银商客服微信验证'
  - '91y银商安全交易教程'
  - '91捕鱼分怎么下分'
  - '91y鱼商收分'
  - '91y充值退分'
  - '91y游戏中心上下'
  - '91y高效上下分攻略'
  - '91y银商老品牌保障'
  - '91y下分客服联系方式'
  - '91y充值回收一站式服务'
  - '91y银商官方认证平台'
  - '91y打鱼全天候客服'
  - '91y银商官方直充'
  - '91y游戏金币秒回收'
  - '91y银商秒到账服务'
  - '91y银商直营渠道'
  - '91y银商信誉保障'
  - '91y游戏安全下分托管'
  - '91y打鱼代充代刷'
  - '91y官方银商合作'
  - '91y游戏上下分优惠'
  - '91y打鱼下分攻略'
  - '91y银商快速到账'
  - '91y游戏币交易群'
  - '91y打鱼上下分平台'
    


# 过期页面判断条件
expired_conditions:
  texts:
    - "页面找不到"
    - "您访问的页面不见了"
    - "内容走丢了"
    - "找不到问题了"
    - "该问题可能已经失效"
    - "后为您自动跳转至首页"
    - "取消跳转"
    - "秒以后自动返回"
    - "404"
    - "Not Found"
    - "nginx"
    - "视频已下线"
    - "请观看其他精彩内容"
    - "很抱歉"
    - "该贴已被删除"
    - "很抱歉，该贴已被删除"
    - "扫码登录请使用 百度贴吧App 扫码登录"
    - "forbidden"
    - "该页面不存在"
    - "哎呀~页面找不到啦!"
    - "页面不存在或已被删除"
  redirect_timeout: 3

# 反馈信息
feedback:
  email: "huiyun@fuyuncn.com"
  description: "网页打不开，提示内容已删除或找不到该网页，请删除快照，且快照包含91y关键词信息为不实内容，误导91y游戏用户，已严重影响到浮云公司的商誉和正常的经营秩序"

# 数据库配置
database:
  path: "DB.sqlite3"
  mysql_user: "network_qa_1056_u"
  mysql_password: "M_9173e5f33c8ebd99"
  connect_timeout: 10 