# 搜索引擎配置
engines:
  baidu:
    url: https://www.baidu.com/
    feedback_url: ""
    cookie_file: baidu.com.txt
  bing:
    url: https://cn.bing.com/
    feedback_url: https://www.bing.com/webmasters/tools/contentremoval
    cookie_file: bing.com.txt
  toutiao:
    url: "https://so.toutiao.com/search?dvpf=pc&source=input&keyword={keyword}"
    feedback_url: ""
    cookie_file: toutiao.com.txt
  so360:
    url: "https://www.so.com"
    feedback_url: https://info.so.com/cache_remove.html
    cookie_file: so.com.txt
  sogou:
    url: "https://www.sogou.com"
    feedback_url: "https://fankui.sogou.com/index.php/web/web/index?type=2"
    cookie_file: sogou.com.txt
    qualification_images:
      - "business_license.jpg"
      - "trademark.jpg"
      - "authorization.jpg"

# 全局配置
qualification_dir: "company_qualifications"  # 资质图片存储目录

# 搜索关键词
keywords:
  - "91y如何快速下分给银商"
  - "91y金币回收银商上下分微信"
  - "91y游戏捕鱼金币回收客服"
  - "91y游戏金币找谁交易"
  - "91y游戏金币在线回收"
  - "91y游戏收分和卖分"
  - "91y游戏商人赚钱吗"
  - "91y游戏能不能赚钱"
  - "91y游戏赢钱了去哪下分"
  - "91y游戏里全网最靠谱的商人"
  - "91y游戏金币退分收分下分"
  - "91y如何转分给另一个人"
  - "91y捕鱼打上一个亿怎么下分"
  - "91y捕鱼游戏分怎么卖"
  - "91y24小时微信上下分银商"
  - "91y如何转分"
  - "91y捕鱼金币怎么换人民币"
  - "91y微信登录怎么下分"
  - "91y游戏上下分加微信送金币"
  - "91y银商找谁开号"
  - "91y金币回收行情价"
  - "91y回收币商哪里找"
  - "91y回收游戏币银商微信"
  - "91y兑现交易比例"
  - "91y银子怎么兑换现金"
  - "91y币怎么兑现"
  - "91y金币怎么换钱"
  - "91y怎么在银商处充值"
  - "91y金币怎么转给银商"
  - "91y游戏币哪里回收"
  - "91y游戏币充值上分下分"
  - "91y新号可以上下分吗"
  - "91y捕鱼上下分信誉"
  - "91y捕鱼限额怎么下分"
  - "91y捕鱼下分平台"
  - "91y上下分诚信银商微信"
  - "91y上分微商"
  - "91y上下分找谁推荐一下"
  - "91y上下分工作人员微信号"
  - "91y上下分客服"
  - "91y商人微信号推荐一个"
  - "91y靠谱商人充值"
  - "91y老店上下分"
  - "91y银商号上下分"
  - "91y诚信老店"
  - "91y充值老店微信"
  - "91y银商充值"
  - "91y游戏上分商"
  - "91y商人代理"
  - '91y游戏上分商 '
  - '91y商人代理 '
  - '91y棋牌银子买卖 '
  - '91y代理买卖分 '
  - '91y买卖上下分Q '
  - '91y银子商家 '
  - '91y银子上下分 '
  - '91y银子商人加微 '
  - '91y上下分信誉好的银商微信 '
  - '91y游戏怎么申请代理银商 '
  - '91y游戏打到分怎么下 '
  - '91y游戏全网客服怎么下分 '
  - '91y游戏全网上下分 '
  - '91y游戏是不是有很多银商 '
  - '91y上下客服怎么联系 '
  - '91y游戏下分客服微信号 '
  - '91y银商微信号 '
  - '91y银商客服 '
  - '91y银子商 '
  - '91y捕鱼诚信商人 '
  - '91y捕鱼上下分诚信商人 '
  - '91y捕鱼上下诚信老店 '
  - '91y捕鱼24小时营业诚信老店 '
  - '91y捕鱼上下分24小时营业 '
  - '91y捕鱼上下分老店24小时营业 '
  - '91y捕鱼上下分靠谱老店 '
  - '91y捕鱼上下分银商老店 '
  - '91y捕鱼上下客服微信 '
  - '91y捕鱼微信下分客服 '
  - '91y捕鱼微信下分 '
  - '91y捕鱼在线上下分 '
  - '91y捕鱼在线微信上下分 '
  - '91y捕鱼24小时回收金币 '
  - '91y捕鱼24小时在线下分 '
  - '91y捕鱼上分下分 '
  - '91y游戏上下 '
  - '91y捕鱼上下 '
  - '91y捕鱼上下威 '
  - '91y捕鱼上下v '
  - '91y捕鱼上下分微信号 '
  - '91y捕鱼上下分怎么转分 '
  - '91y捕鱼上下分客服 '
  - '91y捕鱼上下分银商 '
  - '91y捕鱼怎么转分 '
    


# 过期页面判断条件
expired_conditions:
  texts:
    - "页面找不到"
    - "您访问的页面不见了"
    - "内容走丢了"
    - "找不到问题了"
    - "该问题可能已经失效"
    - "后为您自动跳转至首页"
    - "取消跳转"
    - "秒以后自动返回"
    - "404"
    - "Not Found"
    - "nginx"
    - "视频已下线"
    - "请观看其他精彩内容"
    - "很抱歉"
    - "该贴已被删除"
    - "很抱歉，该贴已被删除"
    - "扫码登录请使用 百度贴吧App 扫码登录"
    - "forbidden"
    - "该页面不存在"
    - "哎呀~页面找不到啦!"
    - "页面不存在或已被删除"
  redirect_timeout: 3

# 反馈信息
feedback:
  email: "huiyun@fuyuncn.com"
  description: "网页打不开，提示内容已删除或找不到该网页，请删除快照，且快照包含91y关键词信息为不实内容，误导91y游戏用户，已严重影响到浮云公司的商誉和正常的经营秩序"

# 数据库配置
database:
  path: "DB.sqlite3" 